def printBaseCountInOrder(ntCount, order ):
    fmtCount = "" 
    for base in order:
        fmtCount += str(ntCount[base]) + " "
    print(fmtCount)
        

dnaStr = "ACTGAGGCCAGTGAGCGGTTCCCTGCCCGTGGCCTAATCCTACTGTCCTTGTCCTATCATAAATTACTCTCGCATCTAAATTGGCCCAGGTGCACCCACGTGAGAGCTGCCTTCGGAAAGTGGGCTCACTTGATTCTTTGCGGGTCGTTGACTTTAAAGTTGTTTTAAGCAATAGAGGCGCGTTCCTCTGCTCGCCAGATCTCGCCATGACCCAAACGGCGGGTGATACGCGAAATAGAGGGACGATCGGCTTCACTCGGAGTTCGTCTCAATCTCATACTATAGGGAGCGCGACGGCCCGGATCCAGGCAGTCGTGGAACGATCCAGCGGAGATAATCGCGGCCTGCCCATCAGTCCATTACGGCCGGCAGCTCCGCCCCGTAACAACTATCAGTGCACGTACGGATACAGTCCAAAATAGTGAATTGCCACGGCCACTTGCAAACCCTCTCTAGTAATCTGACGTGTACCGGCGAACCAAGGCAAGCTAAGAGATCACTTCGGAGAATCGAGACCGGAGAGGTGTGAGGCTGACTGGGCGGTACGTTACATACCTCTAAGCAATGTTGTGATTTTAATATCGGCTAGCTACGTTGGGATCTTATTATCCCGTACGCCCCATAACGACACTTCACCATTTCTTCGGTTAGAACTACCCCCCATTTAAAATATACCTTTGTGAGGATATAGAAGATGATGCGCAATTGTGCTTGGGCAAATGACATCCATACTGTCGATTAACATCGTACTCTGGACTGCCAATCATTCCGAAGACGAGACGAGAATAAACGGATGAGGCACCATCACTAGCATCTTTCAGAGAGACTATCAGATTCCAAGTCTTGCTCAACACTAGTGTTTCAAGCATACCCTACACACAAACCTAATCTGCACCTTAGGGTGCGCTAATCTGTGTACGCATTATGTTCAA"
order = "ACGT"
ntCount = {}

for x in dnaStr:
    if x in ntCount.keys():
        ntCount[x] += 1
    else:
        ntCount[x] = 1

printBaseCountInOrder(ntCount, order )